// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.RescueData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuteDisease")
                        .HasColumnType("int");

                    b.Property<int>("AnimalBite")
                        .HasColumnType("int");

                    b.Property<int>("Burn")
                        .HasColumnType("int");

                    b.Property<int>("CO_Poisoning")
                        .HasColumnType("int");

                    b.Property<int>("Collapse")
                        .HasColumnType("int");

                    b.Property<int>("Drowning")
                        .HasColumnType("int");

                    b.Property<int>("DrugPoisoning")
                        .HasColumnType("int");

                    b.Property<int>("ElectricShock")
                        .HasColumnType("int");

                    b.Property<int>("FallInjury")
                        .HasColumnType("int");

                    b.Property<int>("Falling")
                        .HasColumnType("int");

                    b.Property<int>("GeneralAmbulance")
                        .HasColumnType("int");

                    b.Property<int>("GeneralTrauma")
                        .HasColumnType("int");

                    b.Property<int>("ICUAmbulance")
                        .HasColumnType("int");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MentalDisorder")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("NonTrauma_OHCA")
                        .HasColumnType("int");

                    b.Property<int>("NonTrauma_Other")
                        .HasColumnType("int");

                    b.Property<int>("NotTransported")
                        .HasColumnType("int");

                    b.Property<int>("PregnancyEmergency")
                        .HasColumnType("int");

                    b.Property<int>("Seizure")
                        .HasColumnType("int");

                    b.Property<int>("StabWound")
                        .HasColumnType("int");

                    b.Property<int>("TrafficInjury")
                        .HasColumnType("int");

                    b.Property<int>("Transported")
                        .HasColumnType("int");

                    b.Property<int>("Trauma_OHCA")
                        .HasColumnType("int");

                    b.Property<int>("Trauma_Other")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RescueDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
